In [38]:
import os
import sys
notebook_dir = os.getcwd()
project_root = os.path.abspath(os.path.join(notebook_dir, ".."))

if project_root not in sys.path:
    sys.path.append(project_root)
    sys.path.append(os.path.join(project_root, 'src'))
%load_ext autoreload
%autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [39]:
from src.data_processing import Preprocessing

In [40]:
import pandas as pd

In [41]:
df=pd.read_csv('../data/raw/data.csv')

In [42]:
sf=Preprocessing(df)
sf.transaction_aggregate_features()

2026-05-30 13:52:30,351 - INFO - Successfully engineered aggregate features!

              TransactionId  ... TransactionVariability
0       TransactionId_76871  ...            3042.294251
1       TransactionId_73770  ...            3042.294251
2       TransactionId_26203  ...               0.000000
3         TransactionId_380  ...           17169.241610
4       TransactionId_28195  ...           17169.241610
...                     ...  ...                    ...
95657   TransactionId_89881  ...           22554.029939
95658   TransactionId_91597  ...            2274.756582
95659   TransactionId_82501  ...            2274.756582
95660  TransactionId_136354  ...            3207.920536
95661   TransactionId_35670  ...            3207.920536

[95662 rows x 20 columns]

In [43]:
sf.time_features()

2026-05-30 13:52:31,029 - INFO - successfully completed

              TransactionId         BatchId  ... TransactionMonth TransactionYear
0       TransactionId_76871   BatchId_36123  ...               11            2018
1       TransactionId_73770   BatchId_15642  ...               11            2018
2       TransactionId_26203   BatchId_53941  ...               11            2018
3         TransactionId_380  BatchId_102363  ...               11            2018
4       TransactionId_28195   BatchId_38780  ...               11            2018
...                     ...             ...  ...              ...             ...
95657   TransactionId_89881   BatchId_96668  ...                2            2019
95658   TransactionId_91597    BatchId_3503  ...                2            2019
95659   TransactionId_82501  BatchId_118602  ...                2            2019
95660  TransactionId_136354   BatchId_70924  ...                2            2019
95661   TransactionId_35670   BatchId_29317  ...                2            2019

[95662 rows x 24 columns]